CREATE TABLE computadores (
	PATRIMONIO INT NOT NULL,
    NOME VARCHAR(15),
    MODELO TEXT,
    PROCESSADOR TEXT,
    PLACAMAE TEXT,
    FONTE TEXT,
    ARMAZENAMENTO VARCHAR(20),
    RAM VARCHAR(15),
    PLACADEVIDEO TEXT,
    SO VARCHAR(25),
    CHAVEWIN CHAR(29),
    CHAVEOFF CHAR(29),
    ANTIVIRUS VARCHAR(30),
    SETOR TEXT,
    EMPRESA TEXT,
    PRIMARY KEY(PATRIMONIO)
);

CREATE TABLE usuarios_computadores (
	PATRIMONIO INT,
    USUARIOID INT,
    FOREIGN KEY (PATRIMONIO) REFERENCES COMPUTADORES(PATRIMONIO),
    FOREIGN KEY (USUARIOID) REFERENCES USUARIOS(ID)
);